// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalasReuniaoApi.Data;

#nullable disable

namespace SalasReuniaoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618174535_LimitarTamanhoNome")]
    partial class LimitarTamanhoNome
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("SalasReuniaoApi.Models.SalaReuniao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PossuiProjetor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SalasReuniao");
                });
#pragma warning restore 612, 618
        }
    }
}
